# Sample .travis.yml for R projects

language: r
cache: packages

warnings_are_errors: false
sudo: required

r: - release

env:
  global: 
    - _R_CHECK_FORCE_SUGGESTS_ = false

notifications:
  email:
    on_success: change
    on_failure: change
